device: "cuda"
num-epochs: 200
num-workers: 8
batch-size: 32

learning-rate: 0.0005
weight-decay: 0.0001

use-amp: true
use-augment: true
load-pretrained: true
load-checkpoint: false

load-path: "checkpoints/last-ckpt1.pt"
best-path: "checkpoints/best-ckpt1.pt"
last-path: "checkpoints/last-ckpt1.pt"
